---
- hosts: test
  user: ubuntu
  become: true


  tasks:
  - name: Install docker and pip3
    apt:
      name: ['docker.io', 'python3-pip']
      update_cache: yes

  - name: Install docker-py
    pip:
      name: docker-py

  - name: "Create a directory /opt/app/"
    file:
      path: "{{ item }}"
      state: directory
      mode: '0755'
    with_items:
    - "/opt/app/conf/nginx"
    - "/opt/app/conf/script"
    - "/opt/app/src-image"
    - "/opt/app/www-image"

  - name: Copy file script.sh
    copy:
      src: /tpm/dz/script.sh
      dest: /opt/app/conf/script/script.sh
      owner: root
      group: root
      mode: '0644'

  - name: Copy file nginx.conf
    copy:
      src: /tpm/dz/nginx
      dest: /opt/app/conf/nginx/default
      owner: root
      group: root
      mode: '0644'



  - name: Create container nginx
    docker_container:
      name: nginx
      image: nginx
      ports:
        - "80:80"
      volumes:
        - /opt/app/www-image/:/var/www/
        - /opt/app/conf/nginx/default:/etc/nginx/conf.d/default.conf

  - name: Create container script
    docker_container:
      name: script
      image: ubuntu
      command: /bin/bash /opt/script.sh
      volumes:
      - /opt/app/www-image/:/var/www/
      - /opt/app/src-image/:/app/src/
      - /opt/app/conf/script/script.sh:/opt/script.sh

  - name: Create container ffmpeg
    docker_container:
      name: ffmpeg
      image: jrottenberg/ffmpeg
      command: -i rtsp://wowzaec2demo.streamlock.net/vod/mp4:BigBuckBunny_115k.mov /app/src/bunny_%05d.jpg
      volumes:
      - /opt/app/src-image/:/app/src/



